from abc import ABC


class ImagesPath(ABC):
    BISPO_PRETO: str = 'data/images/chess-bishop-black.png'
    BISPO_BRANCO: str = 'data/images/chess-bishop-white.png'
    REI_PRETO: str = 'data/images/chess-king-black.png'
    REI_BRANCO: str = 'data/images/chess-king-white.png'
    CAVALO_PRETO: str = 'data/images/chess-knight-black.png'
    CAVALO_BRANCO: str = 'data/images/chess-knight-white.png'
    PEAO_PRETO: str = 'data/images/chess-pawn-black.png'
    PEAO_BRANCO: str = 'data/images/chess-pawn-white.png'
    RAINHA_PRETO: str = 'data/images/chess-queen-black.png'
    RAINHA_BRANCO: str = 'data/images/chess-queen-white.png'
    TORRE_PRETO: str = 'data/images/chess-rook-black.png'
    TORRE_BRANCO: str = 'data/images/chess-rook-white.png'
    ICONE_PRETO: str = 'data/images/chess-solid-black.png'
    QUADRADO_PRETO: str = 'data/images/square-black.png'
    QUADRADO_BRANCO: str = 'data/images/square-white.png'
    QUADRADO_FULIGEM: str = 'data/images/square-fuligem.png'
    QUADRADO_MADEIRA: str = 'data/images/square-madeira.png'
    QUADRADO_FULIGEM_SELECIONADO: str = 'data/images/square-fuligem-selecionado.png'
    QUADRADO_MADEIRA_SELECIONADO: str = 'data/images/square-madeira-selecionado.png'
    QUADRADO_FULIGEM_POSSIVEL: str = 'data/images/square-fuligem-possivel.png'
    QUADRADO_MADEIRA_POSSIVEL: str = 'data/images/square-madeira-possivel.png'
